name: Atualizar Dados

on:
  schedule:
    - cron: "0 6 * * 1"  # Executa toda segunda-feira às 6h (UTC)
  workflow_dispatch:

jobs:
  update-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Configurar ambiente Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"

      - name: Instalar dependências
        run: pip install pandas requests

      - name: Executar script de atualização
        run: python data_fetcher.py

      - name: Commit e push dos novos dados
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add data/
          git commit -m "Atualização automática dos dados"
          git push
